import { NextRequest, NextResponse } from 'next/server';
import { cookies } from 'next/headers';
import { getCurrentSession } from '@/lib/auth/session';
import { backendConfig } from '@/lib/auth/config';

async function resolveTokenFromState(
  state: string
): Promise<{ access_token: string; provider: 'gmail' | 'google_calendar' } | null> {
  try {
    const resp = await fetch(
      `${backendConfig.apiBaseUrl}/api/integrations/oauth-state/${encodeURIComponent(state)}`
    );
    if (!resp.ok) return null;
    const json = await resp.json() as {
      success: boolean;
      data?: { access_token: string; provider: string };
    };
    if (!json.data?.access_token) return null;
    return {
      access_token: json.data.access_token,
      provider: json.data.provider as 'gmail' | 'google_calendar',
    };
  } catch {
    return null;
  }
}

export const runtime = 'nodejs';

const WEB_BASE_URL = (process.env.NEXT_PUBLIC_WEB_URL || 'https://hedwigbot.xyz').replace(/\/$/, '');

export async function GET(req: NextRequest): Promise<Response> {
  const code  = req.nextUrl.searchParams.get('code');
  const state = req.nextUrl.searchParams.get('state');
  const error = req.nextUrl.searchParams.get('error');

  if (error) {
    return NextResponse.redirect(`${WEB_BASE_URL}/integrations?integration_error=${encodeURIComponent(error)}`);
  }

  if (!code || !state) {
    return NextResponse.redirect(`${WEB_BASE_URL}/integrations?integration_error=missing_params`);
  }

  const cookieStore = await cookies();
  const oauthCookie = cookieStore.get('oauth_state')?.value;

  let provider: 'gmail' | 'google_calendar';
  let accessToken: string | null = null;

  if (oauthCookie) {
    // ── Web flow: state came from the oauth_state cookie ──────────────────────
    let storedState: { state: string; provider: string; token?: string };
    try {
      storedState = JSON.parse(oauthCookie);
    } catch {
      return NextResponse.redirect(`${WEB_BASE_URL}/integrations?integration_error=invalid_state`);
    }

    if (storedState.state !== state) {
      return NextResponse.redirect(`${WEB_BASE_URL}/integrations?integration_error=state_mismatch`);
    }

    cookieStore.set('oauth_state', '', { maxAge: 0, path: '/' });
    provider = storedState.provider as 'gmail' | 'google_calendar';

    const session = await getCurrentSession();
    accessToken = session.accessToken ?? storedState.token ?? null;
  } else {
    // ── Mobile flow: state was generated by Express /api/integrations/oauth-url
    //    Look up the token from the DB (no cookie required).               ──────
    const mobileSession = await resolveTokenFromState(state);
    if (!mobileSession) {
      return NextResponse.redirect(`${WEB_BASE_URL}/integrations?integration_error=state_expired`);
    }
    accessToken = mobileSession.access_token;
    provider    = mobileSession.provider;
  }

  if (!accessToken) {
    return NextResponse.redirect(`${WEB_BASE_URL}/sign-in`);
  }

  // Forward the code to backend to exchange + store tokens
  const resp = await fetch(`${backendConfig.apiBaseUrl}/api/integrations/oauth/google/callback`, {
    method: 'POST',
    headers: {
      'Content-Type':  'application/json',
      Authorization:   `Bearer ${accessToken}`,
    },
    body: JSON.stringify({ code, redirectUri, provider }),
  });

  if (!resp.ok) {
    const data = await resp.json().catch(() => null) as any;
    const msg  = data?.error || 'oauth_failed';
    return NextResponse.redirect(`${WEB_BASE_URL}/integrations?integration_error=${encodeURIComponent(msg)}`);
  }

  return NextResponse.redirect(`${WEB_BASE_URL}/integrations?integration_connected=${provider}`);
}
